"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import type { PointerEvent as ReactPointerEvent } from "react";
import type { Skill } from "@/lib/skills";
import { categoryById } from "@/lib/taxonomy";
import { NodeIcon, SunIcon } from "./icons";
import { CommandPalette } from "./command-palette";
import { EcosystemFacts } from "./ecosystem-facts";

type Point = { x:number; y:number };
const spread=(count:number)=>count===1?[50]:Array.from({length:count},(_,index)=>24+(52*index)/(count-1));
const layoutGraph=(nodes:Skill["nodes"],edges:Skill["edges"]):Point[]=>{const depths=nodes.map(()=>Number.POSITIVE_INFINITY);depths[0]=0;for(let pass=0;pass<nodes.length;pass++)for(const [from,to] of edges){const a=nodes.findIndex(node=>node.id===from),b=nodes.findIndex(node=>node.id===to);if(a<0||b<0||b<=a||!Number.isFinite(depths[a]))continue;depths[b]=Math.min(depths[b],depths[a]+1)}let fallback=0;for(let index=0;index<depths.length;index++){if(!Number.isFinite(depths[index]))depths[index]=fallback+1;fallback=Math.max(fallback,depths[index])}const maxDepth=Math.max(...depths,1),step=Math.min(18,72/maxDepth),start=50-(step*maxDepth)/2;const groups=new Map<number,number[]>();depths.forEach((depth,index)=>groups.set(depth,[...(groups.get(depth)??[]),index]));const points=nodes.map(()=>({x:50,y:50}));for(const [depth,indexes] of groups){const xs=spread(indexes.length);indexes.forEach((nodeIndex,index)=>{points[nodeIndex]={x:xs[index],y:start+step*depth}})}return points};

export function WorkflowExplorer({ skill }: { skill: Skill }) {
  const inspected=skill.scout!=="Not inspected";
  const scoutLabel=inspected?skill.scout:"Not scouted";
  const [selected,setSelected] = useState(0); const [theme,setTheme] = useState("dark"); const [sheet,setSheet] = useState(false); const [pan,setPan] = useState<Point>({x:0,y:0});
  const viewportRef=useRef<HTMLDivElement>(null); const boardRef=useRef<HTMLDivElement>(null); const drag=useRef<{id:number;x:number;y:number;origin:Point;moved:boolean}|null>(null);
  const coords=useMemo(()=>layoutGraph(skill.nodes,skill.edges),[skill.nodes,skill.edges]);
  const node=skill.nodes[selected];
  useEffect(()=>{document.documentElement.dataset.theme=theme},[theme]);
  const clamp=useCallback((point:Point)=>{const viewport=viewportRef.current,board=boardRef.current;if(!viewport||!board)return point;const nodes=[...board.querySelectorAll<HTMLElement>("[data-node]")];if(!nodes.length)return point;const centersX=nodes.map(node=>node.offsetLeft+node.offsetWidth/2),centersY=nodes.map(node=>node.offsetTop+node.offsetHeight/2),limits={minX:viewport.clientWidth/2-Math.max(...centersX),maxX:viewport.clientWidth/2-Math.min(...centersX),minY:viewport.clientHeight/2-Math.max(...centersY),maxY:viewport.clientHeight/2-Math.min(...centersY)};return{x:Math.max(limits.minX,Math.min(limits.maxX,point.x)),y:Math.max(limits.minY,Math.min(limits.maxY,point.y))}},[]);
  const focusNode=useCallback((index:number,open=true)=>{setSelected(index);if(open)setSheet(true);requestAnimationFrame(()=>{const viewport=viewportRef.current,el=boardRef.current?.querySelector<HTMLElement>(`[data-node="${index}"]`);if(!viewport||!el)return;const viewportRect=viewport.getBoundingClientRect(),mobile=window.matchMedia("(max-width: 700px)").matches,inspector=mobile?document.querySelector<HTMLElement>(".skill-inspector.open"):null,inspectorTop=inspector?.getBoundingClientRect().top??viewportRect.bottom,visibleHeight=Math.max(0,Math.min(viewportRect.bottom,inspectorTop)-viewportRect.top),next={x:viewport.clientWidth/2-(el.offsetLeft+el.offsetWidth/2),y:visibleHeight/2-(el.offsetTop+el.offsetHeight/2)};setPan(clamp(next))})},[clamp]);
  useEffect(()=>{const frame=requestAnimationFrame(()=>{if(window.matchMedia("(max-width: 700px)").matches)setPan({x:0,y:0});else focusNode(0,false)});return()=>cancelAnimationFrame(frame)},[focusNode,skill.slug]);
  useEffect(()=>{const onKey=(event:KeyboardEvent)=>{if(!["ArrowUp","ArrowDown"].includes(event.key)||/INPUT|TEXTAREA|SELECT/.test((event.target as HTMLElement).tagName))return;event.preventDefault();focusNode(Math.max(0,Math.min(skill.nodes.length-1,selected+(event.key==="ArrowDown"?1:-1))),false)};document.addEventListener("keydown",onKey);return()=>document.removeEventListener("keydown",onKey)},[focusNode,selected,skill.nodes.length]);
  useEffect(()=>{const onResize=()=>{if(window.matchMedia("(max-width: 700px)").matches)setPan({x:0,y:0});else setPan(current=>clamp(current))};window.addEventListener("resize",onResize);return()=>window.removeEventListener("resize",onResize)},[clamp]);
  const down=(event:ReactPointerEvent)=>{if(event.button!==0||(event.target as HTMLElement).closest("button,a,[data-node]"))return;event.preventDefault();drag.current={id:event.pointerId,x:event.clientX,y:event.clientY,origin:pan,moved:false};event.currentTarget.setPointerCapture(event.pointerId)};
  const move=(event:ReactPointerEvent)=>{const state=drag.current;if(!state||state.id!==event.pointerId)return;const dx=event.clientX-state.x,dy=event.clientY-state.y;if(Math.hypot(dx,dy)>4)state.moved=true;setPan(clamp({x:state.origin.x+dx,y:state.origin.y+dy}))};
  const up=(event:ReactPointerEvent)=>{if(drag.current?.id===event.pointerId)drag.current=null};
  const line=(from:string,to:string)=>{const a=skill.nodes.findIndex(n=>n.id===from),b=skill.nodes.findIndex(n=>n.id===to),A=coords[a],B=coords[b],horizontal=Math.abs(B.y-A.y)<6;if(horizontal){const direction=B.x>A.x?1:-1;return{x1:A.x+8*direction,y1:A.y,x2:B.x-8*direction,y2:B.y}}const direction=B.y>A.y?1:-1;return{x1:A.x,y1:A.y+5*direction,x2:B.x,y2:B.y-5*direction}};
  return <div className="detail-app">
    <header className="detail-top"><Link href="/" className="brand"><span className="brand-mark">S</span><span>Skillprint</span></Link><span className="detail-skill-name">{skill.name}</span><div className="detail-tools"><CommandPalette compact/><button className="icon-button" onClick={()=>setTheme(theme==="dark"?"light":"dark")} aria-label="Toggle color theme"><SunIcon/></button></div></header>
    <main className="detail-main">
      <section className="detail-intro"><div><p className="eyebrow">{inspected?"Workflow inspection":"Skill blueprint"}</p><h1>{skill.name}</h1><div className="detail-taxonomy"><span className="category-chip detail-category" style={{"--category":skill.color} as React.CSSProperties}><i/>{categoryById[skill.category].label}</span><span className="detail-tags">{skill.tags.map(tag=><b key={tag}>{tag}</b>)}</span></div></div><p>{skill.purpose}</p><div className={`intro-rank ${inspected?"":"pending"}`}><span>Scouter Score</span><strong>{inspected?skill.power.toLocaleString():"—"}</strong><small>{scoutLabel}</small></div></section>
      <div className="detail-grid">
        <section className="workflow-viewport" ref={viewportRef} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} aria-label={`${skill.name} workflow`}>
          <div className="board-label label-a">Start</div><div className="board-label label-b">Work</div><div className="board-label label-c">Result</div>
          <div className="workflow-board" ref={boardRef} style={{transform:`translate3d(${pan.x}px,${pan.y}px,0)`,"--mobile-line-height":`${Math.max(0,(skill.nodes.length-1)*110-64)}px`} as React.CSSProperties}>
            <svg className="workflow-lines" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><defs><marker id="arrow" viewBox="0 0 8 8" refX="7" refY="4" markerWidth="3" markerHeight="3" orient="auto"><path d="M0 0L8 4 0 8z"/></marker></defs>{skill.edges.map(([a,b])=>{const l=line(a,b),from=skill.nodes.findIndex(node=>node.id===a),to=skill.nodes.findIndex(node=>node.id===b),classes=[skill.nodes[selected].id===a||skill.nodes[selected].id===b?"active":"",to<=from?"loop-edge":""].filter(Boolean).join(" ");return <path key={`${a}-${b}`} className={classes} d={`M${l.x1} ${l.y1} C ${l.x1} ${(l.y1+l.y2)/2}, ${l.x2} ${(l.y1+l.y2)/2}, ${l.x2} ${l.y2}`} markerEnd="url(#arrow)"/>})}</svg>
            {skill.nodes.map((item,index)=><button key={item.id} data-node={index} className={`workflow-node ${item.kind} ${selected===index?"selected":""}`} style={{left:`calc(${coords[index].x}% - 74px)`,top:`calc(${coords[index].y}% - 34px)`,"--skill":skill.color} as React.CSSProperties} onClick={()=>focusNode(index)}><span className="node-symbol"><NodeIcon kind={item.kind}/></span><span><small>{item.kind}</small><b>{item.label}</b><em>{item.note}</em></span></button>)}
          </div>
          <div className="drag-hint">Drag canvas to explore</div>
          <nav className="sequence" aria-label="Workflow sequence"><button disabled={selected===0} onClick={()=>focusNode(selected-1,false)} aria-label="Previous step"><i>↑</i> Previous</button><span className="sequence-progress"><small>Step</small><b>{selected+1} / {skill.nodes.length}</b></span><button disabled={selected===skill.nodes.length-1} onClick={()=>focusNode(selected+1,false)} aria-label="Next step">Next <i>↓</i></button></nav>
        </section>
        <aside className={`skill-inspector ${sheet?"open":""}`}><button className="sheet-handle" onClick={()=>setSheet(!sheet)}><span/><small>Selected step</small><b>{node.label}</b><i>{sheet?"×":"↑"}</i></button>
          <details className="inspector-block scout-block"><summary className="block-heading"><p className="eyebrow">{inspected?"Scout report":"Blueprint status"}</p><span>{scoutLabel}</span></summary><div className="scout-content"><div className="scout-line"><div><small>Scouter Score</small><strong style={{color:skill.color}}>{inspected?skill.power.toLocaleString():"—"}</strong></div><dl><dt>Footprint</dt><dd>{skill.footprint}</dd><dt>Recorded installs</dt><dd>{skill.installs.toLocaleString()}</dd></dl></div>{inspected?<div className="quality-list">{skill.qualities.map(q=><div key={q.label}><span>{q.label}</span><i>{Array.from({length:10},(_,i)=><b key={i} className={i<q.score?"on":""} style={{"--skill":skill.color} as React.CSSProperties}/>)}</i><em>{q.word}</em></div>)}</div>:<p className="blueprint-note">This first-pass workflow is derived from catalog metadata. A source inspection will replace it with evidence-backed steps and a Scouter Score.</p>}<p className="method-note">Scouter Score is our assessment. Rank is ecosystem behavior.</p></div></details>
          {skill.ecosystem && <section className="inspector-block ecosystem-block"><div className="block-heading"><p className="eyebrow">Ecosystem</p><span>Repository-level</span></div><EcosystemFacts ecosystem={skill.ecosystem} detailed/><p className="method-note">Interest and maintenance signals stay separate from Scouter Score.</p></section>}
          <section className="inspector-block"><p className="eyebrow">Selected step</p><div className={`selected-title ${node.kind}`}><h2>{node.label}</h2><span>{node.kind}</span></div><p className="selected-summary">{node.summary}</p><dl className="fact-list"><dt>Actor</dt><dd>{node.actor}</dd><dt>Output</dt><dd>{node.output}</dd></dl></section>
          <section className="inspector-block source-block"><div className="block-heading"><p className="eyebrow">{inspected?"Source trace":"Interpretation"}</p><span>{inspected?"Direct source":"Metadata-derived"}</span></div><strong>{inspected?`SKILL.md · ${node.label}`:`Expected stage · ${node.label}`}</strong><blockquote>{node.source}</blockquote>{skill.sourceUrl&&<a className="source-link" href={skill.sourceUrl} target="_blank" rel="noreferrer">View original skill ↗</a>}</section>
          <section className="inspector-block"><p className="eyebrow">Best for</p><p className="best-for">{skill.bestFor}</p><a className="correction-link" href={`https://github.com/jordanranz/skillprint/issues/new?title=${encodeURIComponent(`Category correction: ${skill.name}`)}`} target="_blank" rel="noreferrer">Suggest a classification correction</a></section>
        </aside>
      </div>
    </main>
  </div>;
}
